### ISSUE TITLE
Map should zoom to show all results from a search

### ISSUE THREAD

**Issue by seanhagen** [flyingoctopus/youngagrarians#13]
Had this in initially, but took it out. Easy enough to put back in.

**Comment by seanhagen** [comment]
Search isn't working for me right now. Get the following error:

Started POST "/~youngagr/search" for 127.0.0.1 at 2013-05-09 23:55:21 -0700
Processing by LocationsController#search as _/_
  Parameters: {"terms"=>"Business"}
Completed 500 Internal Server Error in 4ms

TypeError (Cannot visit Regexp):
  app/models/location.rb:22:in `block in search'
  app/models/location.rb:21:in`each'
  app/models/location.rb:21:in `search'
  app/controllers/locations_controller.rb:9:in`search'
